import { LAYOUT_TEMPLATES, type LayoutDocument, type LayoutTemplateName } from "@zcmsorg/schemas";
import type { GeneratedManifest } from "./manifest";

/**
 * The generated theme's source.
 *
 * This is the file that makes the whole GUI-theme feature safe to ship, so it is
 * worth being precise about what it is:
 *
 *   - It is a TEMPLATE, not a compiler. There is no expression from the document
 *     interpolated into it — no widget type becomes an identifier, no prop becomes
 *     code. The only thing the drawing contributes is `layout.json`, which is
 *     DATA the wrapper hands to LayoutRenderer.
 *   - It is the SAME for every drawn theme. Two themes drawn by two strangers
 *     produce byte-identical `index.tsx` and differ only in their JSON. A reviewer
 *     who has read this once has read every drawn theme there will ever be.
 *
 * If a future change makes this file interpolate anything from the document into
 * the emitted SOURCE, that change has re-introduced the arbitrary-code problem the
 * design exists to avoid, and it needs the review a code generator deserves rather
 * than the review a string template gets.
 */

/** Emitted verbatim. The only variation between drawn themes is layout.json. */
const INDEX_TSX = `// GENERATED by @zcmsorg/theme-codegen — do not edit by hand.
//
// This theme was DRAWN in the Z-CMS Theme Editor, not written. Everything specific
// to it lives in ./layout.json (a LayoutDocument); this file is the same in every
// generated theme. It hands the document to the shared widget library and gets out
// of the way.
//
// There is deliberately no logic here. A drawn theme must not be able to express
// anything the widget library cannot already draw — that property is what allows a
// theme somebody made by dragging boxes to be signed and installed at all.
import {
  defineTheme,
  type ArchiveTemplateProps,
  type LayoutProps,
  type PageTemplateProps,
} from "@zcmsorg/theme-sdk";
import { LayoutRenderer, resolveTokens } from "@zcmsorg/theme-widgets";
import type { LayoutDocument, LayoutNode } from "@zcmsorg/schemas";
import manifest from "../theme.json";
import layout from "./layout.json";

const doc = layout as unknown as LayoutDocument;

/** A template the author never drew falls back to \`page\`, exactly as core does. */
function treeFor(name: keyof LayoutDocument["templates"]): LayoutNode[] {
  return (doc.templates[name] ?? doc.templates.page) as LayoutNode[];
}

/**
 * The theme's own tokens, with this SITE's settings on top.
 *
 * The drawing's values are the defaults the manifest declares; an owner who edits
 * "Primary colour" in the admin changes a setting, and it wins here. That is the
 * whole of what a settings form does to a drawn theme.
 */
function tokensFor(settings: Record<string, unknown>) {
  return resolveTokens(doc.tokens, settings);
}

/**
 * Pass-through.
 *
 * A drawn theme has no separate header/footer template yet — an author draws the
 * whole page, header included, in each template. So there is nothing for a Layout
 * to wrap it in, and a Layout that invented a <header> would be putting markup on
 * the page that nobody drew.
 */
function Layout({ children }: LayoutProps) {
  return <>{children}</>;
}

function templateFor(name: keyof LayoutDocument["templates"]) {
  return function Template({ ctx, content }: PageTemplateProps) {
    return (
      <LayoutRenderer
        nodes={treeFor(name)}
        ctx={ctx}
        content={content}
        tokens={tokensFor(ctx.settings as Record<string, unknown>)}
      />
    );
  };
}

/**
 * The archive template gets no \`content\`: an archive is a list of pages, not one
 * page. Widgets bound to "the page being viewed" render nothing here, which is the
 * honest answer rather than a placeholder.
 */
function ArchiveTemplate({ ctx }: ArchiveTemplateProps) {
  return (
    <LayoutRenderer
      nodes={treeFor("archive")}
      ctx={ctx}
      content={null}
      tokens={tokensFor(ctx.settings as Record<string, unknown>)}
    />
  );
}

export default defineTheme({
  manifest: manifest as never,
  Layout,
  templates: {
    page: templateFor("page"),
    home: templateFor("home"),
    post: templateFor("post"),
    archive: ArchiveTemplate,
  },
  // A drawn theme styles no core blocks of its own: \`dynamic/post-content\` renders
  // them through ctx.renderBlocks, which falls back to the runtime's plain
  // renderer. Registering block components here would be code the author never
  // drew.
  blocks: {},
});
`;

/** The wrapper source. Constant — see the note above on why that matters. */
export function emitIndexTsx(): string {
  return INDEX_TSX;
}

/**
 * The document, as the wrapper imports it.
 *
 * Only the templates that were drawn are written, and keys are emitted in a fixed
 * order, so the same drawing serialises to the same bytes on every build. A
 * reproducible build is what lets a reviewer compare two packages and a publisher
 * re-issue one.
 */
export function emitLayoutJson(doc: LayoutDocument): string {
  const templates: Partial<Record<LayoutTemplateName, unknown>> = {};
  for (const name of LAYOUT_TEMPLATES) {
    const tree = doc.templates[name];
    if (tree) templates[name] = tree;
  }
  return JSON.stringify({ version: doc.version, tokens: doc.tokens, templates }, null, 2) + "\n";
}

export function emitThemeJson(manifest: GeneratedManifest): string {
  return JSON.stringify(manifest, null, 2) + "\n";
}

/**
 * The package.json the build needs.
 *
 * `private: true` and no `files`: this is never published to npm — it is packed
 * into a .zcms. React is a peer for the reason every theme's is, and the reason
 * the bundle leaves it external: two Reacts in one render is how a theme system
 * produces "invalid hook call" in production and nowhere else.
 */
export function emitPackageJson(manifest: GeneratedManifest): string {
  return (
    JSON.stringify(
      {
        name: `generated-theme-${manifest.id.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}`,
        version: manifest.version,
        private: true,
        type: "module",
        peerDependencies: { react: "^19.0.0" },
      },
      null,
      2,
    ) + "\n"
  );
}
