import esbuild from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { toDefaultJsxRuntimeImport } from "../../scripts/jsx-runtime-interop.mjs";

/**
 * Builds Aurora into a distributable bundle.
 *
 * Two decisions here are what make a theme installable rather than merely
 * present in the repo:
 *
 * 1. `react` and `react/jsx-runtime` are EXTERNAL. The bundle resolves them from
 *    the host's node_modules at import time, so the theme renders with the same
 *    React instance as site-runtime. Bundling a second copy is how a plugin
 *    system produces errors that only appear in production.
 *
 * 2. The theme ships its own CSS. site-runtime's stylesheet was generated by
 *    scanning site-runtime's source — a theme installed afterwards is invisible
 *    to it, so relying on the host's CSS would render correct markup with no
 *    styling at all. Aurora therefore writes plain CSS into the package and the
 *    runtime serves it from the verified bundle directory.
 *
 * Output is ESM (.mjs) because the runtime imports it by file URL.
 */

const root = path.dirname(new URL(import.meta.url).pathname);

await esbuild.build({
  entryPoints: [path.join(root, "src/index.tsx")],
  outfile: path.join(root, "dist/index.mjs"),
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node22",
  jsx: "automatic",
  external: ["react", "react-dom"],
  logLevel: "warning",
});

// Rewrite react/jsx-runtime to a default import — CJS-safe at run time and
// scanner-safe (no createRequire/node:module). See the helper.
toDefaultJsxRuntimeImport(path.join(root, "dist/index.mjs"));

fs.copyFileSync(path.join(root, "src/theme.css"), path.join(root, "dist/theme.css"));

console.log("aurora: dist/index.mjs + dist/theme.css");
