// GENERATED by scripts/generate-catalog.ts — do not edit by hand.
// Add a language: create src/locales/<code>/, add one entry to locales.json, then
// run `pnpm --filter @zcmsorg/i18n sync`.

import type { Messages } from "./types";

import enAdmin from "./locales/en/admin.json";
import enAppearance from "./locales/en/appearance.json";
import enAuth from "./locales/en/auth.json";
import enCommon from "./locales/en/common.json";
import enContent from "./locales/en/content.json";
import enErrors from "./locales/en/errors.json";
import enMail from "./locales/en/mail.json";
import enMedia from "./locales/en/media.json";
import enPlugins from "./locales/en/plugins.json";
import enSite from "./locales/en/site.json";
import enThemeEditor from "./locales/en/themeEditor.json";
import viAdmin from "./locales/vi/admin.json";
import viAppearance from "./locales/vi/appearance.json";
import viAuth from "./locales/vi/auth.json";
import viCommon from "./locales/vi/common.json";
import viContent from "./locales/vi/content.json";
import viErrors from "./locales/vi/errors.json";
import viMail from "./locales/vi/mail.json";
import viMedia from "./locales/vi/media.json";
import viPlugins from "./locales/vi/plugins.json";
import viSite from "./locales/vi/site.json";
import viThemeEditor from "./locales/vi/themeEditor.json";
import jaAdmin from "./locales/ja/admin.json";
import jaAppearance from "./locales/ja/appearance.json";
import jaAuth from "./locales/ja/auth.json";
import jaCommon from "./locales/ja/common.json";
import jaContent from "./locales/ja/content.json";
import jaErrors from "./locales/ja/errors.json";
import jaMail from "./locales/ja/mail.json";
import jaMedia from "./locales/ja/media.json";
import jaPlugins from "./locales/ja/plugins.json";
import jaSite from "./locales/ja/site.json";
import jaThemeEditor from "./locales/ja/themeEditor.json";

/**
 * Every message, every locale. Server-side only — see the note in
 * scripts/generate-catalog.ts about why this must not reach a browser bundle.
 *
 * A locale that translates only some namespaces lists only those. The missing
 * ones are not stubbed out with empty files: the translator falls back to the
 * base locale key by key, so a half-finished language is a *usable* language.
 */
export const catalog: Record<string, Messages> = {
  "en": {
    admin: enAdmin,
    appearance: enAppearance,
    auth: enAuth,
    common: enCommon,
    content: enContent,
    errors: enErrors,
    mail: enMail,
    media: enMedia,
    plugins: enPlugins,
    site: enSite,
    themeEditor: enThemeEditor,
  },
  "vi": {
    admin: viAdmin,
    appearance: viAppearance,
    auth: viAuth,
    common: viCommon,
    content: viContent,
    errors: viErrors,
    mail: viMail,
    media: viMedia,
    plugins: viPlugins,
    site: viSite,
    themeEditor: viThemeEditor,
  },
  "ja": {
    admin: jaAdmin,
    appearance: jaAppearance,
    auth: jaAuth,
    common: jaCommon,
    content: jaContent,
    errors: jaErrors,
    mail: jaMail,
    media: jaMedia,
    plugins: jaPlugins,
    site: jaSite,
    themeEditor: jaThemeEditor,
  },
};
