// GENERATED by scripts/generate-catalog.ts — do not edit by hand.
// Add a language: create src/locales/<code>/, add one entry to locales.json, then
// run `pnpm --filter @zcmsorg/i18n sync`.

import type { LocaleInfo } from "./types";

/**
 * Namespaces exist so that a translator can pick up one file, finish it, and open
 * a pull request — instead of facing a single thousand-line blob. They also keep
 * contributions from colliding: two people translating different areas of the
 * admin touch different files.
 */
export const NAMESPACES = [
  "admin",
  "appearance",
  "auth",
  "common",
  "content",
  "errors",
  "mail",
  "media",
  "plugins",
  "site",
  "themeEditor",
] as const;

export type Namespace = (typeof NAMESPACES)[number];

/**
 * The namespaces a language must cover before Z-CMS offers it to a user: the
 * chrome you cannot avoid seeing, plus the thing a CMS is for. `coverage` below
 * is the percentage of *these*, not of the whole catalogue — a language can be
 * ready to ship with `plugins` entirely untranslated, and cannot be ready with
 * `auth` untranslated no matter how much else it has done.
 */
export const REQUIRED_NAMESPACES: readonly string[] = ["common","auth","admin","content"];

/** A locale at or above this much of REQUIRED_NAMESPACES is offered. */
export const STABLE_THRESHOLD = 0.95;

/**
 * Every locale in the build, in the order locales.json lists them.
 *
 * Includes experimental ones: a user whose cookie names an experimental locale
 * still gets it, and `<html dir>` still needs to resolve for them.
 */
export const LOCALES: LocaleInfo[] = [
  { code: "en", name: "English", nativeName: "English", dir: "ltr", status: "stable", coverage: 100, flag: "gb" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", dir: "ltr", status: "stable", coverage: 100, flag: "vn" },
  { code: "ja", name: "Japanese", nativeName: "日本語", dir: "ltr", status: "stable", coverage: 100, flag: "jp" },
];

/**
 * What the language switcher offers — the stable ones.
 *
 * A half-translated language is merged and works. It is not *advertised*, because
 * a user who picks their own language from a menu and lands on a mostly-English
 * screen files a bug against the feature, not against the translation.
 */
export const SWITCHER_LOCALES: LocaleInfo[] = LOCALES.filter(
  (l) => l.status === "stable",
);

/** Every locale that resolves, experimental included. */
export const SUPPORTED_LOCALES: readonly string[] = LOCALES.map((l) => l.code);

export function isSupportedLocale(code: string): boolean {
  return SUPPORTED_LOCALES.includes(code);
}
